import type { Metadata } from "next";
import "./globals.css";
import { secondary } from "./fonts";

export const metadata: Metadata = {
  title: "Zeus - KCL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={secondary.className}>
        {children}

      </body>
    </html>
  );
}
