import type { Metadata } from "next";
import "@/app/globals.css";
import { secondary } from "@/app/fonts";
import { Toaster } from "@/components/ui/toaster";
import Topbar from "@/components/custom/nav/topbar";
import Sidebar from "@/components/custom/nav/sidebar";

export const metadata: Metadata = {
  title: "KCL Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={secondary.className}>
        <Sidebar />
        <main className="flex">
          <div className="pl-16 w-full">
            {children}
            <Toaster />
          </div>
        </main>
      </body>
    </html>
  );
}
